spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projem
    username: postgres
    password: ${DB_PASSWORD} # Ortam değişkeninden okumaya devam edecek
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true